### PR TITLE
Use Gatsby to automatically generate a site from markdown

### PR DESCRIPTION
**Pull request by belwase**
PR : https://github.com/filetrust/k8-traffic-generator/issues/49

### CODE REVIEW

**Review by DinisCruz — CHANGES_REQUESTED** [review]
Nice, couple things

Please don’t commit the public pages (I.e. the static files)

Create GitHub Action to commit the generated site to GitHub pages

**Review by DinisCruz — CHANGES_REQUESTED** [review]
Public site pages are still in the commit

**Comment by belwase** [comment]
@DinisCruz  All public files removed

**Review by DinisCruz — APPROVED** [review]
Nice, next can you figure our where to host it 

Ideally it should be here using GitHub pages (with the build workflow done via GitHub Actions)

**Pull request merged**
