### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by silvanayousry**
generating log file and toml configuration file for golang version of traffic generator

### CODE REVIEW

**Comment by yardenshoham** [comment]
Looks like it doesn't do anything as of now so I converted the PR to a draft

**Comment by reem-masoud** [comment]
The code works when it runs with the rest of the files which i uploaded but i don't have permission to PR my code

**Comment by reem-masoud** [comment]
The code works when it runs with the rest of the files which i uploaded but i don't have permission to PR my code

**Comment by reem-masoud** [comment]
The code works when it runs with the rest of the files which i uploaded but i don't have permission to PR my code

**Comment by reem-masoud** [comment]
The code works when it runs with the rest of the files which i uploaded but i don't have permission to PR my code

**Comment by reem-masoud** [comment]
The code works when it runs with the rest of the files which i uploaded but i don't have permission to PR my code

**Comment by dtollaku** [comment]
@reem-masoud you have write access as the rest of the team.

**Comment by silvanayousry** [comment]
I updated the files with the rest of the code ,the part that Reem have worked on ,the code reads urls from text file and generate html files to open pages and it works with the rest of the files i uploaded yesterday

**Review by dinis-cruz-gw — APPROVED** [review]
Good progress, merging

**Pull request merged**
