### PR TITLE
Traffic Generated against Minio.

### PR DESCRIPTION
**Pull request by xuxant**
Python application that make use of the boto3 library to do file action against minio.

### CODE REVIEW

**Review by dinis-cruz-gw — COMMENTED** [review]
Great work

Like the diagram, documentation and use of loop to keep rebuilding files

**Review by yardenshoham — CHANGES_REQUESTED** [review]
As part of #38 please rename the directory from `upwork-devs/susanta_gautam` to `upwork-devs/susanta-gautam`.

**Comment by xuxant** [comment]
Sure. Give me some minutes

**Review by yardenshoham — APPROVED** [review]

**Comment by xuxant** [comment]
@yardenshoham Sir, I have changed the directory  structure.

**Comment by DinisCruz** [comment]
Grate set of commits,

Can you join the project via Upwork so that you can have access to our Slack environment (@dtollaku can help with that)

**Comment by xuxant** [comment]
Sure @DinisCruz Sir,
Do i need to send you my profile link? Miss Doviana has already reach out to me though,

**Pull request merged**
